[package]
name = "aoc15"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
pathfinding = "3.0.5"

[lib]
path = "src/main.rs"
